### ISSUE TITLE
请求更新支持更多版本！

### ISSUE THREAD

**Issue by AUndead** [RoselleMC/TranslateTool#2]
请求更新支持更多版本1.16-1.18.2！！

**Comment by Score2** [comment]
理论都是支持的。
该项目无特殊情况不会继续更新

**Comment by AUndead** [comment]
我在1.18.2版本上无法加载插件！！
[12:39:46] [Server thread/INFO]: 
[12:39:46] [Server thread/ERROR]: Error occurred while enabling TranslateTool v1.2 (Is it up to date?)
java.lang.NoSuchMethodError: 'java.lang.String com.iroselle.TranslateTool.bukkit.util.YamlLoader.parseHeader(java.lang.String)'
	at com.iroselle.TranslateTool.bukkit.util.YamlLoader.loadFromString(YamlLoader.java:55) ~[[T-翻译]TranslateTool-1.3.jar:?]
	at com.iroselle.TranslateTool.bukkit.util.YamlLoader.load(YamlLoader.java:42) ~[[T-翻译]TranslateTool-1.3.jar:?]
	at com.iroselle.TranslateTool.bukkit.util.YamlLoader.load(YamlLoader.java:31) ~[[T-翻译]TranslateTool-1.3.jar:?]
	at com.iroselle.TranslateTool.bukkit.util.YamlLoader.loadConfiguration(YamlLoader.java:87) ~[[T-翻译]TranslateTool-1.3.jar:?]
	at com.iroselle.TranslateTool.bukkit.Config.Config.loadConfig(Config.java:44) ~[[T-翻译]TranslateTool-1.3.jar:?]
	at com.iroselle.TranslateTool.bukkit.TranslateTool.onEnable(TranslateTool.java:36) ~[[T-翻译]TranslateTool-1.3.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[purpur-1.18.2.jar:git-Purpur-1615]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[purpur-1.18.2.jar:git-Purpur-1615]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:669) ~[purpur-1.18.2.jar:git-Purpur-1615]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:436) ~[purpur-1.18.2.jar:git-Purpur-1615]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:352) ~[purpur-1.18.2.jar:git-Purpur-1615]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1179) ~[purpur-1.18.2.jar:git-Purpur-1615]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320) ~[purpur-1.18.2.jar:git-Purpur-1615]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[12:39:46] [Server thread/INFO]: [TranslateTool] Disabling TranslateTool v1.2

**Comment by Score2** [comment]
如果只是用于翻译配置文件，请在1.12版本下使用，效果都是一样的

**Comment by AUndead** [comment]
我的paper1.12.2也无法使用该插件
[13:26:44 INFO]:
[13:26:44 ERROR]: Error occurred while enabling TranslateTool v1.2 (Is it up to date?)
java.lang.NoClassDefFoundError: com/alibaba/fastjson/JSONObject
        at com.iroselle.TranslateTool.bukkit.Config.Config.loadConfig(Config.java:46) ~[?:?]
        at com.iroselle.TranslateTool.bukkit.TranslateTool.onEnable(TranslateTool.java:36) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[patched_1.12.2.jar:git-Paper-1620]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ClassNotFoundException: com.alibaba.fastjson.JSONObject
        at java.net.URLClassLoader.findClass(URLClassLoader.java:445) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:156) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104) ~[patched_1.12.2.jar:git-Paper-1620]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 13 more
[13:26:44 INFO]: [TranslateTool] Disabling TranslateTool v1.2

**Comment by Score2** [comment]
由于项目过于老旧，没法进一步修复。未来也暂无复刻该项目的计划

**Comment by AUndead** [comment]
能给我提供一下视频上所使用的核心么,我想使用这个插件

**Comment by AUndead** [comment]
什么版本最合适translateTool v1.3 我试过了很多版本视乎都没能把它加载上.
